[package]
name = "file_explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.100"
# sysinfo = "0.29.3"
# walkdir = "2.3.3"
